ccdn_user_member_index:
    pattern: /{_locale}/members
    defaults: { _controller: CCDNUserMemberBundle:Member:show, _locale: en }

#ccdn_user_member_paginated:
#    pattern: /{_locale}/members/page/{page}
#    defaults: { _controller: CCDNUserMemberBundle:Member:show, _locale: en, page: 1 }
#
#ccdn_user_member_alpha_index:
#    pattern: /{_locale}/members/filter/{alpha}
#    defaults: { _controller: CCDNUserMemberBundle:Member:showFiltered, _locale: en, page: 1, alpha: a }
#
#ccdn_user_member_alpha_paginated:
#    pattern: /{_locale}/members/filter/{alpha}/page/{page}
#    defaults: { _controller: CCDNUserMemberBundle:Member:showFiltered, _locale: en, page: 1, alpha: a }
