parameters:
    
    ccdn_user_member.gateway.user.class:                      CCDNUser\MemberBundle\Gateway\UserGateway
    ccdn_user_member.manager.user.class:                      CCDNUser\MemberBundle\Manager\UserManager

    ccdn_user_member.component.dashboard.integrator.class:    CCDNUser\MemberBundle\Component\Dashboard\DashboardIntegrator
    
services:

    #
    # Gateways.
    #
    ccdn_user_member.gateway.user:
        class: %ccdn_user_member.gateway.user.class%
        arguments:
            - @doctrine

    #
    # Managers.
    #
    ccdn_user_member.manager.user:
        class: %ccdn_user_member.manager.user.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_user_member.gateway.user
            - %ccdn_user_member.member.list.members_per_page%

    #
    # Dashboard Integrator.
    #
    ccdn_user_member.component.dashboard.integrator:
        class: %ccdn_user_member.component.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }
    