parameters:
    
    ccdn_user_member.component.dashboard.integrator.class:      CCDNUser\MemberBundle\Component\Dashboard\DashboardIntegrator
    ccdn_user_member.component.menu_builder.menu.class:         CCDNUser\MemberBundle\Component\MenuBuilder\Menu
    
services:

    #
    # Dashboard Integrator.
    #
    ccdn_user_member.component.dashboard.integrator:
        class: %ccdn_user_member.component.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }

    #
    # Menu Builder.
    #
    ccdn_user_member.component.menu_builder.menu:
        class: %ccdn_user_member.component.menu_builder.menu.class%
        tags:
            - { name: ccdn_component_menu.menu_builder }
    