parameters:

    # Service Parameters defined in app/config

services:

    #
    # Gateways.
    #
    ccdn_user_member.gateway.user:
        class: %ccdn_user_member.gateway.user.class%
        arguments:
            - @doctrine
            - %ccdn_user_member.entity.user.class%

    #
    # Managers.
    #
    ccdn_user_member.manager.user:
        class: %ccdn_user_member.manager.user.class%
        arguments:
            - @doctrine
            - @security.context
            - @ccdn_user_member.gateway.user
            - %ccdn_user_member.member.list.members_per_page%

    #
    # Dashboard Integrator.
    #
    ccdn_user_member.component.dashboard.integrator:
        class: %ccdn_user_member.component.dashboard.integrator.class%
        arguments:
            - %ccdn_user_member.member.list.requires_login%
        tags:
            - { name: ccdn_component_dashboard.integrator }
