parameters:
    ccdn_user_member.dashboard_integrator.class:            CCDNUser\MemberBundle\Component\Dashboard\DashboardIntegrator

services:

    ccdn_user_member.dashboard_integrator:
        class: %ccdn_user_member.dashboard_integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.registry }
