parameters:
    ccdn_user_member.component.dashboard.integrator.class:            CCDNUser\MemberBundle\Component\Dashboard\DashboardIntegrator

services:

    #
    # Dashboard Integrator.
    #
    ccdn_user_member.component.dashboard.integrator:
        class: %ccdn_user_member.component.dashboard.integrator.class%
        arguments: [@service_container]
        tags:
            - { name: ccdn_component_dashboard.integrator }
